name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8.0.282+8'
      - name: Build with Maven
        run: mvn --batch-mode install
      - run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging        
